config/routes.rb
Rails.application.routes.draw do

  get "public/index"

  devise_for :users

  # The Nela protocol endpoints
  namespace :nela do
    resources :messages, only: [:create] do
      resources :handshakes, only: [:update]
    end
  end  

  # The client application
  resources :conversations do
    resources :messages, only: [:create, :destroy] do
      member do
        get "reply"
      end
    end
  end

  get "up"             => "rails/health#show",        as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest"       => "rails/pwa#manifest",       as: :pwa_manifest

  root "public#index"

end

app/models/conversation.rb
class Conversation < ApplicationRecord

  include Orderable
  include ProtocolReferenceable

  belongs_to :user
  has_many   :messages, dependent: :destroy
  has_one    :latest_message, -> { order(created_at: :desc) }, class_name: 'Message'

  before_validation :set_title, on: :create, unless: -> { title.present? }

  scope :unseen, -> { where('seen_at IS NULL OR updated_at > seen_at') }

  validates :title, presence: true
  validates :user,  presence: true

  accepts_nested_attributes_for :messages, allow_destroy: false, limit: 1

  def seen!
    update_column(:seen_at, Time.current)
  end

  def up_to_date?
    seen_at.present? && seen_at > updated_at
  end

  private

  def set_title
    self.title = messages.first&.title
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_action :set_conversation, only: %i[show]
  after_action  :mark_as_seen,     only: %i[show]

  def index
    @conversations = current_user.conversations.most_recent_first.includes(:latest_message)

    if params[:filter] == 'unseen'
      @conversations = @conversations.unseen
    end
  end

  def show
    @messages = @conversation.messages.most_recent_first
  end

  def new
    @conversation = current_user.conversations.new
    @conversation.messages.build
  end

  def create
    @conversation = current_user.conversations.new(conversation_params)
    @message      = @conversation.messages.first

    @message&.sender = current_user.address

    if @conversation.save
      redirect_to conversation_url(@conversation)
    else
      render :new, status: :unprocessable_entity 
    end
  end

  private

  def set_conversation
    @conversation = current_user.conversations.find(params[:id])
  end

  def mark_as_seen
    @conversation.seen!
  end

  def conversation_params
    params.require(:conversation).permit(
      messages_attributes: [
        :receivers_input, 
        :title,
        :body
      ]
    )
  end
  
end

app/helpers/conversations_helper.rb
module ConversationsHelper

  def unread_indicator(conversation)
    unless conversation.up_to_date?
      tag.span class: "inline-block w-2 h-2 bg-sky-500 rounded-full"
    end
  end

  def tab_menu(params)
    link_css     = "inline-flex items-center justify-center px-4 py-1.5 font-medium rounded-full"
    active_css   = "#{link_css} bg-gray-800 text-white hover:bg-gray-950"
    inactive_css = "#{link_css} bg-gray-100 text-gray-800 hover:bg-gray-200"
  
    tag.div class: "inline-flex gap-x-1 self-start bg-gray-100 rounded-full p-1" do
      concat link_to("All Conversations", conversations_path, class: params[:filter].present? ? inactive_css : active_css)
      concat link_to("Unread Conversations", conversations_path(filter: :unseen), class: params[:filter].present? ? active_css : inactive_css)
    end
  end

  def new_conversation_button
    link_to new_conversation_path, class: "fixed bottom-5 right-5 inline-flex items-center justify-center h-12 w-12 bg-sky-500 text-white rounded-full hover:bg-sky-600" do
      heroicon_tag "plus", class: "w-[24px] h-[24px]"
    end
  end

  def back_to_conversations_button
    link_to conversations_path, class: "fixed bottom-5 left-5 inline-flex items-center justify-center h-12 w-12 bg-gray-800 text-white rounded-full hover:bg-gray-950" do
      heroicon_tag "arrow-left", class: "w-[24px] h-[24px]"
    end
  end

end

app/views/conversations/_form.html.erb
<%= form_with(model: [@conversation], local: true, class: "flex flex-col gap-y-5") do |form| %>

  <%= form_errors_for @conversation %>

  <%= form.fields_for :messages do |message_fields| %> 
    <div class="flex items-center gap-x-1">
      <span class="font-medium">From</span>
      <span class="text-fuchsia-500"><%= current_user.address %></span>
    </div>
    
    <%= form_group do %>
      <%= message_fields.label :title, "Subject" %>
      <%= message_fields.text_field :title %>
    <% end %>

    <%= form_group do %>
      <%= message_fields.label :receivers_input, "To" %>
      <em class="text-sm text-gray-500">(comma-separated)</em>
      <%= message_fields.text_field :receivers_input %>
    <% end %>

    <%= form_group do %>
      <%= message_fields.label :body, "Message" %>
      <%= message_fields.text_area :body, rows: 10 %>
    <% end %>
  <% end %>

  <%= form.submit 'Start Conversation' %>

<% end %>

app/views/conversations/index.html.erb
<% content_for :title, "Conversations" %>
<%= heroicon_tag "chat-bubble-oval-left-ellipsis", class: "w-10 h-10" %>
<%= h1 "Conversations" %>

<%= tab_menu params %>

<% if @conversations.any? %>
  <% @conversations.each do |conversation| %>
    <div class="flex flex-col gap-y-2 w-full">    
      <div class="flex gap-x-3 w-full">
        <%= avatar(conversation.latest_message.sender) %>
        <div class="flex flex-col gap-y-1 w-full min-w-0">
          <div class="flex flex-col gap-y-0 w-full min-w-0">
            <div class="flex items-center justify-between">
              <span class="text-fuchsia-500"><%= conversation.latest_message.sender %></span>
              <div class="flex items-center gap-x-1">
                <%= handshake_icon conversation.latest_message %>
                <span class="text-gray-400 text-sm">
                  <%= conversation.latest_message.created_at.strftime("%b %d, %Y, %I:%M %p") %>
                </span>
              </div>
            </div>
            <div class="flex items-center gap-x-1.5">
              <%= unread_indicator(conversation) %>
              <%= link_to conversation.title || "Untitled", conversation_path(conversation), class: "truncate font-medium" %>
            </div>
          </div>
          <%= paragraph do %>
            <%= conversation.latest_message.body.truncate(130) %>
          <% end %>
          <div class="flex items-center gap-x-1.5 w-full">
            <%= link_to reply_conversation_message_path(conversation, conversation.latest_message), class: "self-start inline-flex gap-x-1 text-sky-500 items-center underline whitespace-nowrap hover:text-sky-600" do %>
              <%= heroicon_tag "arrow-uturn-left", class: "w-[20px] h-[20px]" %> 
              Reply to
            <% end %>
            <div class="text-gray-500 rounded-full"><%= addresses_group reply_to(conversation.latest_message) %></div>
          </div>
        </div>
      </div>
    </div>
    <div class="pl-[52px]"><%= separator %></div>
  <% end %>
<% else %>
  <%= highlight "Oops, no conversations yet", "face-frown" %>
<% end %>

<%= new_conversation_button %>

app/views/conversations/new.html.erb
<%= heroicon_tag "chat-bubble-oval-left-ellipsis", class: "w-10 h-10" %>
<%= h1 "New Conversation" %>
<%= render "form", conversation: @conversation %>

<%= back_to_button conversations_path %>

app/views/conversations/show.html.erb
<% content_for :title, "Conversation" %>
<%= heroicon_tag "chat-bubble-oval-left-ellipsis", class: "w-10 h-10" %>
<%= h1 "Conversation" %>

<% @messages.each do |message| %>
  <div class="flex flex-col gap-y-2 w-full">    
    <div class="flex gap-x-3 w-full">
      <%= avatar(message.sender) %>
      <div class="flex flex-col gap-y-1 w-full min-w-0">
        <div class="flex flex-col gap-y-0 w-full min-w-0">
          <div class="flex items-center justify-between">
            <span class="text-fuchsia-500"><%= message.sender %></span>
            <div class="flex items-center gap-x-1">
              <%= handshake_icon message %>
              <span class="text-gray-400 text-sm">
                <%= message.created_at.strftime("%b %d, %Y, %I:%M %p") %>
              </span>
            </div>
          </div>
          <div class="truncate font-medium"><%= message.title %></div>
        </div>
        <%= formatted_paragraph message.body %>
        <div class="flex items-center gap-x-1.5 w-full">
          <%= link_to reply_conversation_message_path(@conversation, message), class: "self-start inline-flex gap-x-1 text-sky-500 items-center underline whitespace-nowrap hover:text-sky-600" do %>
            <%= heroicon_tag "arrow-uturn-left", class: "w-[20px] h-[20px]" %> 
            Reply to
          <% end %>
          <div class="text-gray-500 rounded-full"><%= addresses_group reply_to(message) %></div>
        </div>
      </div>
    </div>
  </div>
  <div class="pl-[52px]"><%= separator %></div>
<% end %>

<%= back_to_button conversations_path %>
<%= new_conversation_button %>